Repository Klepac-Ceraj-Lab/Resonance, pull requests merged in 2022-08, with the labels that each got.

#45 [WIP] Brain wrangle
  Manifest.toml
  Project.toml
  figures/brain_noo_pcoa.png
  figures/brain_pcoa.png
  figures/brainplots/Brain-Stem_pca1_absrel.png
  figures/brainplots/CSF_pca1_absrel.png
  figures/brainplots/EstimatedTotalIntraCranialVol_pca1_absrel.png
  figures/brainplots/Left-Accumbens-area_pca1_absrel.png
  figures/brainplots/Left-Amygdala_pca1_absrel.png
  figures/brainplots/Left-Caudate_pca1_absrel.png
  figures/brainplots/Left-Cerebellum-Cortex_pca1_absrel.png
  figures/brainplots/Left-Cerebellum-White-Matter_pca1_absrel.png
  figures/brainplots/Left-Hippocampus_pca1_absrel.png
  figures/brainplots/Left-Lateral-Ventricle_pca1_absrel.png
  figures/brainplots/Left-Pallidum_pca1_absrel.png
  figures/brainplots/Left-Putamen_pca1_absrel.png
  figures/brainplots/Left-Thalamus_pca1_absrel.png
  figures/brainplots/Left-VentralDC_pca1_absrel.png
  figures/brainplots/Left-choroid-plexus_pca1_absrel.png
  figures/brainplots/Right-Accumbens-area_pca1_absrel.png
  figures/brainplots/Right-Amygdala_pca1_absrel.png
  figures/brainplots/Right-Caudate_pca1_absrel.png
  figures/brainplots/Right-Cerebellum-Cortex_pca1_absrel.png
  figures/brainplots/Right-Cerebellum-White-Matter_pca1_absrel.png
  figures/brainplots/Right-Hippocampus_pca1_absrel.png
  figures/brainplots/Right-Lateral-Ventricle_pca1_absrel.png
  figures/brainplots/Right-Pallidum_pca1_absrel.png
  figures/brainplots/Right-Putamen_pca1_absrel.png
  figures/brainplots/Right-Thalamus_pca1_absrel.png
  figures/brainplots/Right-VentralDC_pca1_absrel.png
  figures/brainplots/Right-choroid-plexus_pca1_absrel.png
  figures/brainplots/lhCortexVol_pca1_absrel.png
  figures/brainplots/lhCorticalWhiteMatterVol_pca1_absrel.png
  figures/brainplots/outliers.csv
  figures/brainplots/rhCortexVol_pca1_absrel.png
  figures/brainplots/rhCorticalWhiteMatterVol_pca1_absrel.png
  figures/sp_mated_cog.png
  notes/08-permanovas.jl
  notes/09-associations.jl
  notes/10-fsea.jl
  notes/Y-data_requests.jl
  notes/Z-Khula-pres.jl
  src/startup.jl
Labels: Paper

#47 Machinelearning
  Manifest.toml
  Project.toml
  figures/prediction_futurecogscore_testset_comparison.png
  figures/prediction_futurecogscore_trainset_comparison.png
  notes/01-metadata_wrangle.jl
  notes/D01-data_description.jl
  notes/D02-prediction_current_cogScores.jl
  notes/D03-prediction_future_cogScores.jl
  notes/D031-prepare_futurecogscore_prediction_df.jl
  notes/W-longform.jl
  src/Resonance.jl
  src/prediction.jl
  src/startup.jl
Labels: Paper, Analysis

#57 Figure 1 first draft
  .gitignore
  Manifest.toml
  figures/Figure1.png
  figures/Figure1.svg
  notes/Figure1.md
  src/Resonance.jl
  src/files.jl
  src/omnibus.jl
  src/plotting.jl
Labels: Paper, Figures

#63 Figure 1 mods
  Manifest.toml
  Project.toml
  figures/Figure1.png
  figures/Figure1.svg
  figures/fig1a_placeholder.png
  notes/Figure1.md
  src/data_loading.jl
  src/omnibus.jl
  src/plotting.jl
Labels: Paper, Figures

#64 Added Resonance.load(::Neuroimaging) to load_data.jl and Brain.jl
  src/brain.jl
  src/data_loading.jl
Labels: Paper, Package

#59 GLMs - nothing significant
  Manifest.toml
  Project.toml
  notes/99-exports.jl
  notes/Figure1.md
  notes/Figure2.md
  src/data_loading.jl
Labels: Paper, Analysis, Figures

#62 Figure 2 - Functions / FSEA
  Manifest.toml
  Project.toml
  figures/Figure3.png
  figures/Figure3.svg
  notes/Figure3.md
  src/genefamilies.jl
  src/plotting.jl
Labels: Paper, Figures

#65 More figure 1 modifications
  figures/Figure1.png
  figures/Figure1.svg
  notes/Figure1.md
Labels: Paper, Figures

#67 New brain segmentation + load(::Neuroimaging)
  notes/01-metadata_wrangle.jl
  src/Resonance.jl
  src/brain.jl
  src/data_loading.jl
Labels: Paper, Package
