Repository Klepac-Ceraj-Lab/Resonance, pull requests merged in 2023-03, with the labels that each got.

#119 Manuscript revisions
  manuscript/main.tex
  manuscript/tex/zotero_library.bib
Labels: Paper

#122 Sean comments
  manuscript/main.tex
Labels: Paper

#128 Fig4 legends
  manuscript/Figure4.md
  manuscript/assets/Figure4.png
  src/Resonance.jl
  src/files.jl
  src/plotting.jl
Labels: Figures

#136 Add tex document to generate supplemental figures
  manuscript/.gitignore
  manuscript/supplement.tex
Labels: Paper

#134 Add author contributions and package references
  Manifest.toml
  Project.toml
  Setup/bin/derive.jl
  manuscript/main.tex
  manuscript/zotero.bib
  src/Resonance.jl
Labels: Paper

#138 Figure fixes
  manuscript/Figure1.md
  manuscript/Figure2.md
  manuscript/Figure3.md
  manuscript/Figure4.md
  manuscript/assets/Figure1.png
  manuscript/assets/Figure1A.jpg
  manuscript/assets/Figure3.png
  manuscript/assets/Figure4.png
  manuscript/main.tex
  src/Resonance.jl
  src/microbiomejl_interface.jl
Labels: Figures

#140 Read-through
  manuscript/Figure1.md
  manuscript/Figure3.md
  manuscript/main.tex
Labels: Paper

#144 Ml changes readthrough
  manuscript/main.tex
Labels: Paper

#141 Readme updates
  README.md
  Setup/README.md
Labels: Package

#154 Tweaks
  manuscript/main.tex
  manuscript/supplement.tex
Labels: Paper

#161 Final read through
  manuscript/main.tex
  manuscript/supplement.tex
Labels: Paper, Figures, Package
